export const images = [
  {
    src: 'https://telegra.ph/file/049641df035cf67a15286.jpg',
    width: 320,
    height: 174,
    tags: [{ value: 'Kirish', title: 'Kirish' }],
    caption: 'Maktabning kirish qismi',
  },
  {
    src: 'https://telegra.ph/file/65295c6d4338dc55648a9.png',
    width: 380,
    height: 200,
    // tags: [{ value: '', title: '' }],
    caption: 'Maktab fayesi',
  },
  {
    src: 'https://telegra.ph/file/31cf9b75f7da0afff7eef.jpg',
    width: 320,
    height: 204,
    tags: [{ value: 'Sport', title: 'Sport' }],
    caption: 'Sport zal',
  },
  {
    src: 'https://telegra.ph/file/314b2d4adea2455bfdc7f.jpg',
    width: 320,
    height: 174,
    tags: [{ value: 'Sport', title: 'Sport' }],
    caption: 'Stadion',
  },
  {
    src: 'https://telegra.ph/file/ef3ac989c0b2017c41225.jpg',
    width: 320,
    height: 140,
    // tags: [{ value: '', title: '' }],
    caption: 'Faollar zali',
  },
  {
    src: 'https://telegra.ph/file/0d078992d91f909df76ea.jpg',
    width: 320,
    height: 150,
    // tags: [{ value: '', title: '' }],
    caption: 'Maktab oshxonasi',
  },
  {
    src: 'https://telegra.ph/file/dcaf08b8b434bcbd51a6b.png',
    width: 320,
    height: 200,
    // tags: [{ value: '', title: '' }],
    caption: 'Direktor xonasi',
  },
  {
    src: 'https://telegra.ph/file/d3188e1b536d1b1efee7e.png',
    width: 320,
    height: 120,
    // tags: [{ value: '', title: '' }],
    caption: 'Ustozlar xonasi',
  },
  {
    src: 'https://telegra.ph/file/d0a1635645206377fbdb2.png',
    width: 320,
    height: 110,
    // tags: [{ value: 'IT', title: '' }],
    caption: 'Informatika xonasi',
  },
  {
    src: 'https://telegra.ph/file/9bc1630d843c7b58c25a7.png',
    width: 320,
    height: 150,
    // tags: [{ value: '', title: '' }],
    caption: 'Dars xonasi',
  },
  {
    src: 'https://telegra.ph/file/4881929f15b2e09bd0d14.png',
    width: 320,
    height: 174,
    // tags: [{ value: '', title: '' }],
    caption: 'Dars vaqti',
  },
  {
    src: 'https://telegra.ph/file/81a6ea5f5d4f3dc8bad8a.png',
    width: 320,
    height: 129,
    tags: [{ value: 'O`simliklar', title: 'O`simliklar' }],
    caption: 'Daraxlar',
  },
  {
    src: 'https://telegra.ph/file/288d923265cb32b669383.png',
    width: 320,
    height: 148,
    tags: [{ value: 'O`simliklar', title: 'O`simliklar' }],
    caption: 'Maktab bog`i',
  },
  {
    src: 'https://telegra.ph/file/ef477ca6fa09fb14e9106.png',
    width: 320,
    height: 136,
    tags: [{ value: 'O`simliklar', title: 'O`simliklar' }],
    caption: 'Turli xil o`simliklar',
  },
  {
    src: 'https://telegra.ph/file/798fdb0b84a81f678ac08.jpg',
    width: 320,
    height: 170,
    // tags: [{ value: '', title: '' }],
    caption: 'Tadbirlardan lavha',
  },
  {
    src: 'https://telegra.ph/file/878539aeff4c277fb55d9.jpg',
    width: 320,
    height: 110,
    // tags: [{ value: '', title: '' }],
    caption: '11 sinf o`quvchilari',
  },
  {
    src: 'https://telegra.ph/file/6c4aab5972e3915051a93.jpg',
    width: 320,
    height: 120,
    tags: [{ value: 'Bitiruv', title: 'Bitiruv' }],
    caption: '11-sinf o`quvchilari bitiruvi',
  },
  {
    src: 'https://telegra.ph/file/456af9c8dce867a032a13.jpg',
    width: 320,
    height: 110,
    tags: [{ value: 'Bitiruvchilar', title: 'Bitiruvchilar' }],
    caption: '11-sinf o`quvchilari bitiruvi',
  },
  {
    src: 'https://telegra.ph/file/33e1758a90a12917b62b4.jpg',
    width: 320,
    height: 135,
    tags: [{ value: 'Bitiruvchilar', title: 'Bitiruvchilar' }],
    caption: '11-sinf o`quvchilari bitiruvi',
  },
  {
    src: 'https://telegra.ph/file/ed6c6df4c96d668b88490.jpg',
    width: 320,
    height: 115,
    tags: [{ value: 'Boshlang`ich', title: 'Boshlang`ich' }],
    caption: '1-sinf o`quvchilari',
  },
  {
    src: 'https://telegra.ph/file/0b87adc17d3ea3f252805.jpg',
    width: 320,
    height: 145,
    tags: [{ value: 'Bitiruvchilar', title: 'Bitiruvchilar' }],
    caption: 'Maktab bitiruvchilari',
  },
  {
    src: 'https://telegra.ph/file/c34e8a519627d96956d24.jpg',
    width: 320,
    height: 145,
    tags: [
      { value: 'Ustozlar', title: 'Ustozlar' },
      { value: 'Tadbir', title: 'Tadbir' },
    ],
    caption: 'Maktabimiz ustozlari',
  },
  {
    src: 'https://telegra.ph/file/7040d6e8b9d8fca57318e.jpg',
    width: 320,
    height: 170,
    tags: [
      { value: 'Ustozlar', title: 'Ustozlar' },
      { value: 'Tadbir', title: 'Tadbir' },
    ],
    caption: 'Maktabimiz ustozlari',
  },
  {
    src: 'https://telegra.ph/file/38e1af56f65f84e3cd7b1.jpg',
    width: 320,
    height: 160,
    tags: [
      { value: 'Direktor', title: 'Direktor' },
      { value: '1-sinf', title: '1-sinf' },
    ],
    caption: 'Boshlang`ich sinf o`quvchilari',
  },
  {
    src: 'https://telegra.ph/file/55417d6d7bd12d34c1e46.jpg',
    width: 320,
    height: 140,
    tags: [
      { value: 'Vazir', title: 'Vazir' },
      { value: 'Direktor', title: 'Direktor' },
    ],
    caption: 'Bosh vazir, maktab direktori va ustozlar',
  },
];
