export const images = [
  {
    src: '/src/assets/images/1.jpg',
    width: 320,
    height: 174,
    tags: [{ value: 'Kirish', title: 'Kirish' }],
    caption: 'Maktabning kirish qismi',
  },
  {
    src: '/src/assets/images/2.png',
    width: 380,
    height: 200,
    // tags: [{ value: '', title: '' }],
    caption: 'Maktab fayesi',
  },
  {
    src: '/src/assets/images/3.jpg',
    width: 320,
    height: 204,
    tags: [{ value: 'Sport', title: 'Sport' }],
    caption: 'Sport zal',
  },
  {
    src: '/src/assets/images/4.jpg',
    width: 320,
    height: 174,
    tags: [{ value: 'Sport', title: 'Sport' }],
    caption: 'Stadion',
  },
  {
    src: '/src/assets/images/5.jpg',
    width: 320,
    height: 140,
    // tags: [{ value: '', title: '' }],
    caption: 'Faollar zali',
  },
  {
    src: '/src/assets/images/6.jpg',
    width: 320,
    height: 150,
    // tags: [{ value: '', title: '' }],
    caption: 'Maktab oshxonasi',
  },
  {
    src: '/src/assets/images/7.png',
    width: 320,
    height: 200,
    // tags: [{ value: '', title: '' }],
    caption: 'Direktor xonasi',
  },
  {
    src: '/src/assets/images/8.png',
    width: 320,
    height: 120,
    // tags: [{ value: '', title: '' }],
    caption: 'Ustozlar xonasi',
  },
  {
    src: '/src/assets/images/9.png',
    width: 320,
    height: 110,
    // tags: [{ value: 'IT', title: '' }],
    caption: 'Informatika xonasi',
  },
  {
    src: '/src/assets/images/10.png',
    width: 320,
    height: 150,
    // tags: [{ value: '', title: '' }],
    caption: 'Dars xonasi',
  },
  {
    src: '/src/assets/images/11.png',
    width: 320,
    height: 174,
    // tags: [{ value: '', title: '' }],
    caption: 'Dars vaqti',
  },
  {
    src: '/src/assets/images/12.png',
    width: 320,
    height: 129,
    tags: [{ value: 'O`simliklar', title: 'O`simliklar' }],
    caption: 'Daraxlar',
  },
  {
    src: '/src/assets/images/13.png',
    width: 320,
    height: 148,
    tags: [{ value: 'O`simliklar', title: 'O`simliklar' }],
    caption: 'Maktab bog`i',
  },
  {
    src: '/src/assets/images/14.png',
    width: 320,
    height: 136,
    tags: [{ value: 'O`simliklar', title: 'O`simliklar' }],
    caption: 'Turli xil o`simliklar',
  },
  {
    src: '/src/assets/images/15.jpg',
    width: 320,
    height: 170,
    // tags: [{ value: '', title: '' }],
    caption: 'Tadbirlardan lavha',
  },
  {
    src: '/src/assets/images/16.jpg',
    width: 320,
    height: 110,
    // tags: [{ value: '', title: '' }],
    caption: '11 sinf o`quvchilari',
  },
  {
    src: '/src/assets/images/17.jpg',
    width: 320,
    height: 120,
    tags: [{ value: 'Bitiruv', title: 'Bitiruv' }],
    caption: '11-sinf o`quvchilari bitiruvi',
  },
  {
    src: '/src/assets/images/18.jpg',
    width: 320,
    height: 110,
    tags: [{ value: 'Bitiruvchilar', title: 'Bitiruvchilar' }],
    caption: '11-sinf o`quvchilari bitiruvi',
  },
  {
    src: '/src/assets/images/19.jpg',
    width: 320,
    height: 135,
    tags: [{ value: 'Bitiruvchilar', title: 'Bitiruvchilar' }],
    caption: '11-sinf o`quvchilari bitiruvi',
  },
  {
    src: '/src/assets/images/20.jpg',
    width: 320,
    height: 115,
    tags: [{ value: 'Boshlang`ich', title: 'Boshlang`ich' }],
    caption: '1-sinf o`quvchilari',
  },
  {
    src: '/src/assets/images/21.jpg',
    width: 320,
    height: 145,
    tags: [{ value: 'Bitiruvchilar', title: 'Bitiruvchilar' }],
    caption: 'Maktab bitiruvchilari',
  },
  {
    src: '/src/assets/images/22.jpg',
    width: 320,
    height: 145,
    tags: [
      { value: 'Ustozlar', title: 'Ustozlar' },
      { value: 'Tadbir', title: 'Tadbir' },
    ],
    caption: 'Maktabimiz ustozlari',
  },
  {
    src: '/src/assets/images/23.jpg',
    width: 320,
    height: 170,
    tags: [
      { value: 'Ustozlar', title: 'Ustozlar' },
      { value: 'Tadbir', title: 'Tadbir' },
    ],
    caption: 'Maktabimiz ustozlari',
  },
  {
    src: '/src/assets/images/24.jpg',
    width: 320,
    height: 160,
    tags: [
      { value: 'Direktor', title: 'Direktor' },
      { value: '1-sinf', title: '1-sinf' },
    ],
    caption: 'Boshlang`ich sinf o`quvchilari',
  },
  {
    src: '/src/assets/images/25.jpg',
    width: 320,
    height: 140,
    tags: [
      { value: 'Vazir', title: 'Vazir' },
      { value: 'Direktor', title: 'Direktor' },
    ],
    caption: 'Bosh vazir, maktab direktori va ustozlar',
  },
];
