const content = {
  ru: {
    navbar: {
      home: 'Главная',
      news: 'Новости',
      students: 'Ученики',
      teachers: 'Учителя',
      contact: 'Контакты',
      administration: 'Администрация',
      contact_button: 'Контакт',
      about: 'Про школу',
      school: 'Школа',
      xodim: 'Сотрудники',
      kirish: 'Войти',
      kontakt: 'Контакт',
    },
    intro: {
      heading: 'Добро пожаловать в общеобразовательную среднюю школу № 182.',
      text: 'Общеобразовательная средняя школа №182, расположенная в городе Ташкенте, Республика Узбекистан.',
    },
    news: {
      heading: 'Новости школы',
      more: 'Более',
      teachers: 'Учителя',
      moreinfo: 'Более',
      aboutschool: 'Информация о школе',
      beststudents: 'Самые активные ученики',
      admins: 'Администрация школы',
      teachers: 'Лучшие учителя',
    },
    stats: {
      teachers: 'Преподавательский состав',
      students: 'учеников',
      winner: 'призер олимпиад',
      graduated: 'Те, кто вошел в ОТМ',
      heading: 'Статистика',
    },
    students: {
      heading: 'Лучшие ученики школы',
      text1: 'Ученик',
      text2: 'класса',
      teacher: 'классний руководител',
      more: 'Более',
    },
    form: {
      heading: 'Есть какие-то вопросы ?',
      fio: 'и.ф.о',
      phone: 'номер телефона',
      email: 'электронная почта',
      comment: 'оставить коментарий',
      send: 'Отправлять',
    },
    footer: {
      location: 'Местоположение',
      social: 'Мы в соцсетях',
    },
    neosoft: {
      made: 'Сделано NEOSOFT™️',
    },
  },
  uz: {
    navbar: {
      home: 'Бош саҳифа',
      news: 'Янгиликлар',
      students: ' Фаол ўқувчилар',
      teachers: 'Устозлар',
      contact: 'Боғланиш',
      administration: 'Мактаб маъмурияти',
      contact_button: 'Боғланиш',
      about: 'Мактаб ҳақида',
      school: 'Мактаб',
      xodim: 'Xодимлар',
      kirish: 'Тизимга кириш',
      kontakt: 'Контакт',
    },
    intro: {
      heading: '182-сонли умумий ўрта таълим мактабига ҳуш келибсиз. ',
      text: 'Ўзбекистон Республикаси Тошкент шахрида жойлашган 182-сонли умумий ўрта таълим мактаби.',
    },
    news: {
      heading: 'Мактаб янгиликлари',
      more: 'Кўпроқ',
      teachers: 'Устозлар',
      moreinfo: 'Батафсил',
      aboutschool: 'Мактаб ҳақида маълумотлар',
      beststudents: 'Енг фаол ўқувчилар',
      admins: 'Мактаб Маъмурияти',
      teachers: 'Енг яхши устозлар',
    },
    stats: {
      teachers: 'Педагогик ходимлар',
      students: 'ўқувчилар',
      winner: 'oлимпиада совриндори',
      graduated: 'ОТМга кирганлар',
      heading: 'Statistika',
    },
    students: {
      heading: 'Мактабнинг фаол ўқувчилари',
      text1: '',
      text2: 'синф ўқувчиси',
      teacher: 'синф раҳбари',
      more: 'Кўпроқ',
    },
    form: {
      heading: 'Саволлар борми?',
      fio: 'ф. и. о',
      phone: 'телефон рақам',
      email: 'електрон почта',
      comment: 'изоҳ қолдиринг',
      send: 'Юбориш',
    },
    footer: {
      location: 'Манзил',
      social: 'Биз ижтимоий тармоқларда',
    },
    neosoft: {
      made: 'NEOSOFT™ томонидан ишлаб чиқарилган',
    },
  },
};

export default content;
